version: '3'

services:
  client:
    image: node:8
    volumes:
      - ../client:/usr/lib/client
    working_dir: /usr/lib/client
    ports:
      - 3000:3000
    command: yarn start
  server:
    image: node:8
    volumes:
      - ../server:/usr/lib/server
    working_dir: /usr/lib/server
    ports:
      - 3001:3001
    command: yarn start
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:10
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
      - ../server/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
