version: '3'

services:
  db:
    image: postgres:10-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
      - ../server/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
